services:
    kucera.monolog.blue_screen:
        class: Tracy\BlueScreen
        factory: [Tracy\Debugger, getBlueScreen]

    kucera.monolog.tracy.logger_helper:
        class: Nella\MonologTracy\Tracy\LoggerHelper
        arguments:
            - '@kucera.monolog.blue_screen'
            - %kernel.logs_dir%/tracy

    kucera.monolog.handler.blue_screen_handler_prototype:
        abstract: true
        class: Nella\MonologTracy\BlueScreenHandler
        arguments:
            - '@kucera.monolog.tracy.logger_helper'
            - DEBUG
            - true
