services:
    nella.monolog_tracy.blue_screen:
        class: Tracy\BlueScreen
        factory: [ %nella.monolog_tracy.tracy.blue_screen_factory.service%, create ]

    nella.monolog_tracy.tracy.blue_screen_factory:
        class: Nella\MonologTracy\Tracy\BlueScreenFactory

    nella.monolog_tracy.blue_screen_handler:
        class: Nella\MonologTracy\BlueScreenHandler
        arguments:
            - %nella.monolog_tracy.tracy.logger_helper.service%
            - %nella.monolog_tracy.blue_screen_handler.level%
            - %nella.monolog_tracy.blue_screen_handler.bubble%

    nella.monolog_tracy.tracy.logger_helper:
        class: Nella\MonologTracy\Tracy\LoggerHelper
        arguments:
            - %nella.monolog_tracy.blue_screen.service%
            - %nella.monolog_tracy.log_directory%
